DS2BRAIN/ds2

.gitignore
=> 14 doc: Add directory to .gitignore

backend/src/errorResponseList.py
change invalid email error text
=> 5 "Invalid email" is shown even though I wrote the correct email.

frontend_app/src/views/Table/ModelTable.js
https://github.com/DS2BRAIN/ds2/issues/11
Error occurred by leftover code that activate api model request for "object-detection" project.
After deleted, it works well (request deactivated)
=> 11 fix error on model list page (send requests for all models error)

frontend_app/src/components/Function/globalFunc.js, frontend_app/src/views/AIProject/Process.js
https://github.com/DS2BRAIN/ds2/issues/29
=> 29 It is not possible to choose the AutoML function from second time

frontend_app/src/components/Navbars/NavMenu.js, frontend_app/src/components/Navbars/Navbar.js
https://github.com/DS2BRAIN/ds2/issues/67
=> 67 fix: GNB active effect error

frontend_app/public/index.html, frontend_app/src/App.js, frontend_app/src/components/User/PasswordCard.js
https://github.com/DS2BRAIN/ds2/issues/69
=> 69 fix: Enterprise version channel talk exposure error

frontend_app/src/components/Templates/Templates.js, frontend_app/src/views/Dataconnector/Dataconnector.js
https://github.com/DS2BRAIN/ds2/issues/76
=> 76 (EL175) Example text should not be shown if there's no available examples.

frontend_app/src/layouts/SignUp.js
https://github.com/DS2BRAIN/ds2/issues/82
회원가입 비밀번호 입력칸에 마우스를 올렸을때 영문 출력 및 이메일 중복확인 버튼 영문 출력
=> 82 (EL160) Translation error in sign-up page.

frontend_app/src/components/PredictModal/API.js
https://github.com/DS2BRAIN/ds2/issues/84
(only image classification & no predicted  value) show top label through calculation in front-end.
이미지 분류 학습 중 생성된 이미지예측을 시도할 경우  예측값 정보 상단에 숫자 0이 나타남
=> 84 (EL151) Prediction result error on the prediction of image classification.

frontend_app/src/views/Table/SummaryTable.js
https://github.com/DS2BRAIN/ds2/issues/86
=> 86 Fix to display 0 instead of - if min is 0 in summary

frontend_app/src/views/SkyhubAI/OpsPannel/OpsPannel.js
https://github.com/DS2BRAIN/ds2/issues/92
=> 92 fix: Fix an issue where ops project name change and delete button were hidden

frontend_app/src/components/PredictModal/API.js
https://github.com/DS2BRAIN/ds2/issues/88
=> 88 (EL165) .jpg files are also available for image prediction.

frontend_app/src/views/SkyhubAI/OpsPannel/OpsPannel.js
https://github.com/DS2BRAIN/ds2/issues/94
=> 94 Set ops project default name, error message handling in case of blank value when changing

frontend_app/src/views/Setting/Group.js
https://github.com/DS2BRAIN/ds2/issues/96
=> 96 Modify group invitation table td sorting and add "Action" column name

frontend_app/src/language/translation.en.json, frontend_app/src/language/translation.ko.json, frontend_app/src/views/Setting/UserInfo.js
https://github.com/DS2BRAIN/ds2/issues/91
(EL169) Make admin account not be deleted
(EL170)
=> 91 (EL169) Make admin account not be deleted

frontend_app/src/language/translation.en.json, frontend_app/src/language/translation.ko.json, frontend_app/src/views/Table/ModelTable.js
https://github.com/DS2BRAIN/ds2/issues/99
=> 99 fix: Add missing translation of error message in model table

frontend_app/src/views/Table/ModelTable.js
https://github.com/DS2BRAIN/ds2/issues/101
(EL174) ModelList progress bar calculation logic has to be modified
(EL175) default setting columns in modeltable keep repeating and adding.
=> 101 (EL174) ModelList progress bar calculation logic has to be modified

frontend_app/src/views/Dataconnector/Dataconnector.js
https://github.com/DS2BRAIN/ds2/issues/103
=> 103 (EL178) Tooltip on active button is not disappeared until hover again.

frontend_app/src/components/PredictModal/API.js
https://github.com/DS2BRAIN/ds2/issues/105
(EL178) Filter Korean text on the textfield of prediction API modal (CSV)
=> 105 (EL178) Filter Korean text on the textfield of prediction API modal (CSV)

frontend_app/src/views/JupyterProject/JupyterPannel/History/History.js, frontend_app/src/views/SkyhubAI/OpsPannel/OpsPannel.js
https://github.com/DS2BRAIN/ds2/issues/107
delete dashboard based on feedback (port 19999 is unaccessible)
=> 107 (EL177) Delete result dashboard for jupyter & Ops.

frontend_app/src/views/AIProject/AutoMLProject.js, frontend_app/src/views/Dataconnector/Dataconnector.js, frontend_app/src/views/JupyterProject/JupyterProjectList.js, frontend_app/src/views/Labelling/LabelprojectList.js, frontend_app/src/views/SkyhubAI/OpsProjectList.js
https://github.com/DS2BRAIN/ds2/issues/109
[row number deleted on the table of page - ]
dataconnector page
labelling page
train page
verify page
deploy page
jupyter page
=> 109 (EL179) Delete row number on tables

frontend_app/src/views/Table/Detail.js
https://github.com/DS2BRAIN/ds2/issues/117
=> 117 (EL192) Percentage value error on related column - Feature importance tab in Detail page.

frontend_app/src/views/Dataconnector/DataModalsFileAdd.js
https://github.com/DS2BRAIN/ds2/issues/122
=> 122 (EL202) File example images do not show on console web page.

frontend_app/src/components/Modal/LicenseRegisterModal.js, frontend_app/src/views/SkyhubAI/OpsPannel/OpsPannel.js
https://github.com/DS2BRAIN/ds2/issues/124
=> 124 (EL205) License register modal overflow error.

frontend_app/src/assets/jss/custom.js, frontend_app/src/views/SkyhubAI/OpsProjectList.js
https://github.com/DS2BRAIN/ds2/issues/127
=> 127 (EL212) date value on table in deploy page error.

frontend_app/src/views/Table/ModelTable.js
https://github.com/DS2BRAIN/ds2/issues/129
=> 129 (EL213) value error if column is changed from error rate to accuracy.

frontend_app/src/views/Labelling/LabelDetail.js, frontend_app/src/views/Labelling/LabelList.js, frontend_app/src/views/Labelling/LabelMember.js, frontend_app/src/views/Labelling/LabelSetting.js
https://github.com/DS2BRAIN/ds2/issues/131
=> 131 (EL214) label project defail dashboard page errors

frontend_app/src/components/Navbars/NavMenu.js, frontend_app/src/components/Notifications/NotiPopover.js, frontend_app/src/views/Setting/Manager.js
https://github.com/DS2BRAIN/ds2/issues/133
=> 133 (EL217) Manage page column header sorting error.

frontend_app/src/assets/css/control-custom.css
https://github.com/DS2BRAIN/ds2/issues/135
=> 135 fix: Fix the problem that the textarea font color inside the feedback is not visible

frontend_app/src/language/translation.en.json, frontend_app/src/views/Labelling/LabelDetail.js, frontend_app/src/views/Project/NewProject.js
https://github.com/DS2BRAIN/ds2/issues/137
=> 137 (EL236) set minimal number of auto-labeling.

frontend_app/src/views/Labelling/LabelList.js
https://github.com/DS2BRAIN/ds2/issues/140
=> 140 fix: Fix labeling file addition and deletion errors

frontend_app/src/assets/jss/custom.js, frontend_app/src/views/Market/MarketList.js
https://github.com/DS2BRAIN/ds2/issues/145
=> 145 refactor & fix in market product list page.

frontend_app/src/views/Dataconnector/Dataconnector.js
https://github.com/DS2BRAIN/ds2/issues/148
=> 148 (EL243) all checked checkbox in dataset page malfunciton error.

frontend_app/src/views/Setting/Manager.js
https://github.com/DS2BRAIN/ds2/issues/150
=> 150 (EL244) manage page click, info left error.

frontend_app/src/language/translation.en.json, frontend_app/src/language/translation.ko.json, frontend_app/src/views/Labelling/LabelList.js, frontend_app/src/views/Labelling/LabelPreview.js, frontend_app/src/views/Market/MarketDetail.js
https://github.com/DS2BRAIN/ds2/issues/156
=> 156 (EL219) class sorting in label data list table.

frontend_app/src/redux/reducers/projects.js, frontend_app/src/views/AIProject/AutoMLProject.js
https://github.com/DS2BRAIN/ds2/issues/160
=> 160 Integrate tableheads as managing standard for the table pages.

frontend_app/src/views/Dataconnector/Dataconnector.js
https://github.com/DS2BRAIN/ds2/issues/162
=> 162 fix: My Data page was displayed when returning after leaving the dataset public data page

frontend_app/src/views/Setting/HyperParametersForm.js
https://github.com/DS2BRAIN/ds2/issues/165
=> 165 fix: Incorrect numbering when adding optimizer to manual setup in learning project

frontend_app/src/language/translation.en.json, frontend_app/src/views/Dataconnector/Dataconnector.js
https://github.com/DS2BRAIN/ds2/issues/138
=> 138 refactor & fix error in dataset page.

frontend_app/src/views/Labelling/LabelDetail.js, frontend_app/src/views/Labelling/LabelSetting.js
https://github.com/DS2BRAIN/ds2/issues/170
=> 170 (EL 262~264) Labelproject dashboard error.

frontend_app/src/components/Notifications/NotiPopover.js, frontend_app/src/language/translation.en.json, frontend_app/src/language/translation.ko.json, frontend_app/src/redux/reducers/user.js
https://github.com/DS2BRAIN/ds2/issues/175
=> 175 Notificaton maximum number error (above 30 notifications).

frontend_app/src/views/Dataconnector/Dataconnector.js
https://github.com/DS2BRAIN/ds2/issues/174
=> 174 Manage dataset list table page. & delete rownum in public data table

frontend_app/src/views/Labelling/LabelprojectList.js
https://github.com/DS2BRAIN/ds2/issues/178
=> 178 fix label project data table header size percentage size

frontend_app/src/views/Labelling/LabelprojectList.js
https://github.com/DS2BRAIN/ds2/issues/180
=> 180 manage label project list table by tableheads.

frontend_app/src/views/Dataconnector/Dataconnector.js
https://github.com/DS2BRAIN/ds2/issues/182
=> 182 integrate dateset table (private + public).

frontend_app/src/assets/css/material-dashboard-react-dark.css, frontend_app/src/components/Notifications/NotiList.js, frontend_app/src/views/Setting/Manager.js, frontend_app/src/views/Setting/UserInfo.js
https://github.com/DS2BRAIN/ds2/issues/186
=> 186 fix user setting part

frontend_app/src/views/Labelling/LabelDetail.js, frontend_app/src/views/Labelling/LabelList.js, frontend_app/src/views/Labelling/LabelprojectList.js
https://github.com/DS2BRAIN/ds2/issues/188
=> 188 Label detail dashboard page

frontend_app/src/components/Footer/Footer.js, frontend_app/src/language/translation.en.json, frontend_app/src/language/translation.ko.json
https://github.com/DS2BRAIN/ds2/issues/190
=> 190 (EL269) fix address of DSLAB office in footer

frontend_app/src/components/PredictModal/API.js, frontend_app/src/views/Table/Detail.js
https://github.com/DS2BRAIN/ds2/issues/192
=> 192 (EL268) fix error in Train, predict page.

frontend_app/src/components/Footer/Footer.js, frontend_app/src/components/Modal/LicenseRegisterModal.js, frontend_app/src/components/Navbars/NavMenu.js, frontend_app/src/components/User/PasswordCard.js, frontend_app/src/language/i18n.js, frontend_app/src/layouts/Admin.js, frontend_app/src/layouts/BrowserError.js, frontend_app/src/layouts/SignIn.js, frontend_app/src/layouts/SignUp.js, frontend_app/src/routes.js, frontend_app/src/views/Table/ModelTable.js
https://github.com/DS2BRAIN/ds2/issues/194
=> 194 activate functions which are hidden to get GS verification.
